Fix/telegram
Taiwan-Ebook-Lover/TaiwanEbookSearch-API pull request #9
Opened 2020-08-23 17:13 UTC by ast850328

Need a better template

Now:
Keywords: **被討厭的勇氣**
Search Time: 2020/08/24 00:52:02
Process Time: 5.33s
Total: 193
User Agent: insomnia/2020.3.3
Search ID: `wSEyqIwkmnhAvq3vCcYz`
Link: [🔗](https://yuer.tw/sunnyworm.png)
Bookstore Result: 
✅  博客來 (20 | 0.38s),
✅  Readmoo 讀墨 (100 | 1.71s),
✅  樂天 kobo (12 | 0.63s),
✅  Taaze 讀冊生活 (3 | 5.32s),
✅  BOOKWALKER (0 | 0.46s),
✅  Google Play 圖書 (50 | 0.87s),
✅  Pubu 電子商城 (6 | 0.57s),
✅  HyRead 電子書 (2 | 0.52s)

2020-08-24 14:14 UTC, passerbyid requested changes

2020-08-24 14:14 UTC, passerbyid commented on src/firestore.ts
> +  data = JSON.parse(JSON.stringify(data, (key, value) => (value === undefined ? null : value)));
避免重新賦值予參數。

2020-08-24 14:14 UTC, YuerLee commented on src/stores/readmoo.ts
> +const id = 'readmoo' as const;
與此次合併目標無關，建議另開/推。

2020-08-24 14:14 UTC, YuerLee commented on src/stores/readmoo.ts
> +          .children('.thumbnail')
請確認有執行 prettier 。

2020-08-24 14:52 UTC, ast850328 commented on src/stores/readmoo.ts
> +          .children('.thumbnail')
抱歉，收到了

2020-08-24 14:52 UTC, ast850328 commented on src/stores/readmoo.ts
> +const id = 'readmoo' as const;
好的，不要兇

2020-08-24 14:53 UTC, ast850328 commented on src/firestore.ts
> +  data = JSON.parse(JSON.stringify(data, (key, value) => (value === undefined ? null : value)));
Got it

2020-08-25 00:15 UTC, passerbyid requested changes

2020-08-25 00:15 UTC, passerbyid commented on src/firestore.ts
> +      formattedData.id = res.id;
別直接改值，避免不預期的情況。
```typescript
.then(({id}) => ({...formattedData, id })) 
```

2020-08-25 03:23 UTC, ast850328 commented on src/firestore.ts
> +      formattedData.id = res.id;
好

2020-08-25 11:09 UTC, passerbyid requested changes

2020-08-25 11:09 UTC, passerbyid commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules/typescript/lib"
與此 PR 無關。

2020-08-25 11:28 UTC, passerbyid approved these changes

2020-08-25 13:43 UTC, merged